[package]
name = "rust_crate"
version = "0.1.0"
authors = ["RobotHuang <1183598761@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mylib = {path = "./mylib"}
rust-crypto = "0.2"