[package]
name = "use_try_join"
version = "0.1.0"
authors = ["RobotHuang <1183598761@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
tokio = {version = "1.5.0", features = ["full"]}